#!/usr/bin/env python3
"""Redirect map — the single source for both generated pages and hosting config.

Why this exists
---------------
The site is served by GitHub Pages, which **ignores** a `_redirects` file.
Aliases written only there return 404 in production. So redirects are declared
once here and build-blog.py emits two things from this dict:

  1. a real HTML page at each source path, carrying
     `<meta http-equiv="refresh">` + `<link rel="canonical">` + `noindex`
     — this works on every static host, GitHub Pages included
  2. `_redirects` in Netlify/Cloudflare format, so hosts that *do* support
     server-side redirects answer with a true 301 instead of a meta refresh

Because both come from one dict, the two can never disagree (§29).

Conventions
-----------
* Key: source path, no trailing slash, no scheme (`/formats`).
* Value: destination path that exists on disk (`/product-formats.html`).
* Every destination is validated by scripts/validate-site.py — a redirect
  pointing at a missing page is a build error, not a warning.
* Add an entry only for a URL that has been published, linked from outreach,
  or is a plausible typo. Redirects are not a substitute for navigation.
"""

# ── Landing-page aliases ────────────────────────────────────────────────
# The canonical URL is /china-supplement-sourcing.html. These exist because
# /supplier-verification and /supplier-due-diligence appear in navigation copy,
# email outreach and older links.
DUE_DILIGENCE = "/china-supplement-sourcing.html"

# ── Formats catalogue ───────────────────────────────────────────────────
# Relocated off the homepage in V2.1; /capabilities was the old section anchor.
FORMATS = "/product-formats.html"

REDIRECTS = {
    # Supplier due diligence
    "/supplier-verification": DUE_DILIGENCE,
    "/supplier-due-diligence": DUE_DILIGENCE,
    "/alibaba-supplier-review": DUE_DILIGENCE,
    "/supplier-review": DUE_DILIGENCE,
    # Formats catalogue
    "/capabilities": FORMATS,
    "/product-formats": FORMATS,
    "/formats": FORMATS,
    # Pillar hubs — extension-less and .html forms of the directory URLs
    "/product-development.html": "/product-development/",
    "/ingredient-sourcing.html": "/ingredient-sourcing/",
    "/supplement-manufacturing.html": "/supplement-manufacturing/",
    "/china-supplement-supply-chain.html": "/china-supplement-supply-chain/",
    "/supplement-industry-consulting.html": "/supplement-industry-consulting/",
    # Blog index variants
    "/insights": "/blog/",
    "/articles": "/blog/",
}

# Host-level rules. GitHub Pages cannot express these; they are written into
# `_redirects` for hosts that can. Kept here so the whole redirect story lives
# in one place.
HOST_RULES = [
    ("https://www.suppbridge.com/*", "https://suppbridge.com/:splat"),
]


def redirect_pairs():
    """(source, destination) pairs for generated HTML redirect pages.

    Skips sources that collide with a real directory of the same name, so a
    redirect can never silently shadow a page that actually exists.
    """
    return sorted(REDIRECTS.items())


def netlify_format():
    """The `_redirects` file body, derived from the same map."""
    lines = [
        "# GENERATED by build-blog.py from content/redirects.py — do not edit.",
        "# GitHub Pages ignores this file; the generated HTML redirect pages are",
        "# what makes these aliases work there.",
        "",
        "# Host-level rules",
    ]
    for src, dst in HOST_RULES:
        lines.append(f"{src}  {dst}  301")
    lines += ["", "# Path aliases"]
    for src, dst in redirect_pairs():
        lines.append(f"{src}  {dst}  301")
        lines.append(f"{src}/  {dst}  301")
    return "\n".join(lines) + "\n"
