#!/usr/bin/env python3
"""Sync shared navigation + footer into the hand-authored pages.

Usage: python3 scripts/sync-chrome.py [--check]

Why this exists
---------------
The blog index, article pages and the five pillar pages are generated by
build-blog.py and therefore always share one navigation and one footer.
The handful of hand-authored pages (homepage, sourcing landing page,
formats catalogue, regulatory detail, thank-you) are edited directly — so
without this step their nav/footer drift out of sync with the rest of the
site the moment a pillar is renamed or a CTA changes.

This script rewrites exactly four regions in those files:

    <nav class="nav" id="nav"> … </nav>
    <footer class="site-footer"> … </footer>
    <!-- analytics:begin --> … <!-- analytics:end -->  (before </head>)
    favicon set + web manifest + theme colour (inserted once if missing)

The analytics region is spliced in from content/analytics.py and is absent
whenever no measurement ID is configured.

and ensures the shared icon symbols (#i-chev, #i-arrow, #i-menu) exist in
each page's inline sprite. Everything else is left untouched.

`--check` reports drift and exits non-zero without writing, so it can be
wired into CI or run before a deploy.
"""

import os
import re
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE_DIR)

from content.chrome import nav_block as CHROME_NAV, footer_block as CHROME_FOOTER, SPRITE_SYMBOLS  # noqa: E402
from content.analytics import splice as sync_analytics_block  # noqa: E402

PAGES = [
    # (relative path, is the page that owns the homepage anchors)
    ("index.html", True),
    ("china-supplement-sourcing.html", False),
    ("product-formats.html", False),
    ("regulatory/index.html", False),
    ("thanks.html", False),
]

NAV_RE = re.compile(r'<nav class="nav" id="nav">.*?</nav>', re.S)
FOOTER_RE = re.compile(r'<footer class="site-footer">.*?</footer>', re.S)
SPRITE_RE = re.compile(r'(<svg width="0" height="0"[^>]*>\n)(.*?)(</svg>)', re.S)


def sync_sprites(html):
    """Make sure the three shared symbols are present in the inline sprite."""
    m = SPRITE_RE.search(html)
    if not m:
        return html, False
    head, body, tail = m.group(1), m.group(2), m.group(3)
    missing = [s for s in SPRITE_SYMBOLS if f'id="{s.split(chr(34))[1]}"' not in body]
    if not missing:
        return html, False
    additions = "\n".join("  " + s for s in missing) + "\n"
    new = head + additions + body.rstrip("\n") + "\n" + tail
    return html[:m.start()] + new + html[m.end():], True


# Head assets every page shares. Each is checked on its own rather than in
# one blob, so a page that already carried the favicon still picks up the
# later additions (the legacy .ico, the web manifest, the OS theme colour)
# instead of being skipped wholesale for "already having an icon".
HEAD_ASSETS = (
    '<link rel="icon" type="image/svg+xml" href="/images/favicon.svg">',
    '<link rel="icon" type="image/png" sizes="48x48" href="/images/favicon.png">',
    '<link rel="icon" href="/images/favicon.ico" sizes="any">',
    '<link rel="apple-touch-icon" href="/images/apple-touch-icon.png">',
    '<link rel="manifest" href="/images/site.webmanifest">',
    '<meta name="theme-color" content="#12100E">',
)


def sync_head_assets(html):
    """Idempotently ensure the shared head assets exist, one entry at a time."""
    if "</head>" not in html:
        return html, False
    missing = [a for a in HEAD_ASSETS if a not in html]
    if not missing:
        return html, False
    block = "\n".join("  " + a for a in missing) + "\n"
    return html.replace("</head>", block + "</head>", 1), True


def sync_page(rel, is_root, check_only):
    """`is_root` marks the page that owns the homepage anchors, so its nav
    links stay `#value` rather than `/#value`."""
    page_nav = CHROME_NAV(is_root)
    page_footer = CHROME_FOOTER(is_root)

    path = os.path.join(BASE_DIR, rel)
    if not os.path.exists(path):
        return rel, "MISSING FILE", False
    with open(path, encoding="utf-8") as f:
        original = f.read()

    html = original
    notes = []

    if NAV_RE.search(html):
        if NAV_RE.search(html).group(0) != page_nav:
            html = NAV_RE.sub(lambda _: page_nav, html, count=1)
            notes.append("nav")
    else:
        notes.append("NO-NAV")

    if FOOTER_RE.search(html):
        if FOOTER_RE.search(html).group(0) != page_footer:
            html = FOOTER_RE.sub(lambda _: page_footer, html, count=1)
            notes.append("footer")
    else:
        notes.append("NO-FOOTER")

    html, sprite_changed = sync_sprites(html)
    if sprite_changed:
        notes.append("sprite")

    # The analytics block is configuration-driven (content/site_config.py),
    # so the hand-authored pages have to be re-spliced whenever it changes —
    # including when it is turned off, which removes the block entirely.
    html, analytics_changed = sync_analytics_block(html)
    if analytics_changed:
        notes.append("analytics")

    html, favicon_changed = sync_head_assets(html)
    if favicon_changed:
        notes.append("head-assets")

    changed = html != original
    if changed and not check_only:
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)
    return rel, (", ".join(notes) if notes else "in sync"), changed


def main():
    check_only = "--check" in sys.argv
    drift = 0
    print("Nav/footer sync" + (" (check only)" if check_only else "") + "\n")
    for rel, is_root in PAGES:
        name, result, changed = sync_page(rel, is_root, check_only)
        mark = "~" if changed else "="
        print(f"  {mark} {name:<34} {result}")
        if changed:
            drift += 1
    print()
    if drift:
        if check_only:
            print(f"DRIFT: {drift} page(s) out of sync. Run: python3 scripts/sync-chrome.py")
            return 1
        print(f"Updated {drift} page(s).")
    else:
        print("All pages in sync.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
